### ISSUE TITLE
Uppercase does not affects zero

### ISSUE THREAD

**Issue by codesignist** [Maheshkumar-Kakade/number-to-text#14]
If number equals zero uppercase does not affects zero.
```javascript
console.log(numberToText.convertToText(0,` {case:"upperCase"}) ); //returns "Zero"
```

**Comment by Maheshkumar-Kakade** [comment]
Do you have npm account? Want to add you as a contributor.

**Comment by codesignist** [comment]
Yes. Same name, codesignist.
Please add.
https://www.npmjs.com/~codesignist
